import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { UserDetailContext } from "./_context/UserDetailContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const publishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

  if (!publishableKey) {
    return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center min-h-screen bg-gray-100`}>
          <div className="p-8 bg-white shadow-lg rounded-xl text-center">
            <h1 className="text-2xl font-bold text-red-600 mb-4">Configuration Required</h1>
            <p className="text-gray-600">Please set the <code className="bg-gray-200 px-1 rounded">NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY</code> environment variable to proceed with deployment.</p>
          </div>
        </body>
      </html>
    );
  }

  return (
    <ClerkProvider publishableKey={publishableKey}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Provider>
          {children}
        </Provider>
         
        </body>
      </html>
    </ClerkProvider>
  );
}
